version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./streamlit:/app

volumes:
  mysql_data: